name: Deploy Laravel to EC2

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 檢出程式碼
        uses: actions/checkout@v3

      - name: 設置 SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
      - name: 部署到 EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /var/www/member_forfam/backend  # 進入 Laravel 專案目錄
            git fetch --all
            sudo git reset --hard origin/main # 放棄當前所有檔案與commit，更新為遠端最新版
            git pull  # 確認是否up to date
            php artisan migrate  # 執行資料庫遷移
            sudo systemctl restart apache2  # 重啟 Apache
          EOF
