name: Deploy Laravel to EC2

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 檢出程式碼
        uses: actions/checkout@v3

      - name: 設置 SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
      - name: 部署到 EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /var/www/member_check/backend  # 進入你的 Laravel 專案目錄
            git pull  # 拉取最新程式碼
            composer install --no-dev --optimize-autoloader  # 安裝 PHP 套件
            php artisan migrate --force  # 執行資料庫遷移
            php artisan config:cache  # 快取設定
            php artisan route:cache  # 快取路由
            chmod -R 775 storage bootstrap/cache  # 確保權限
            sudo systemctl restart apache2  # 重啟 Apache
          EOF
